config/routes.rb
Rails.application.routes.draw do
  
  # root to: "main#index"
  root 'friends#index'
  resources :friends
  get "sign_up" ,to: "registrations#new"
  post "sign_up",to: "registrations#create"
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  get "sign_in" ,to: "sessions#new"
  post "sign_in",to: "sessions#create"
  delete "logout", to: "sessions#destroy"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name,  presence: true
  validates :email, :contact_number, presence: true , uniqueness: true
  validate :email_format

  private
  def email_format
    unless email =~ /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/
      errors.add(:email, 'is not in the correct format')
    end
  end
  
  
end

app/models/permission_request.rb
class PermissionRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :friends, dependent: :destroy

    before_create :create_session_token
    validates :session_token, uniqueness: true, allow_nil: true

    validates :email, presence: true,uniqueness: true;
    validate :email_format
    
    def create_session_token
        self.session_token = SecureRandom.hex(10) 
    end

    private

    def email_format
        unless email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
        errors.add(:email, "is not a valid email address")
        end
    end
   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    before_action :check_session_timeout
    

    def set_current_user
      if session[:session_token]
        @current_user = User.find_by(session_token: session[:session_token])
        if @current_user
          Current.user = @current_user
          Rails.logger.info "Current selected user data is #{Current.user.inspect}"
        else
          Rails.logger.info "Didn't have current user selected"
          reset_session
        end

      else
        Rails.logger.info "didn't recived the ssession[:session_token]"
      end
         
    end

    def user_logged_in?
        redirect_to sign_in_path, alert: 'Please sign in first' if Current.user.nil?
    end

    def check_session_timeout
        if @current_user
          Rails.logger.info "current user details #{@current_user.inspect}"
            if @current_user.last_seen_at &&  @current_user.last_seen_at < SESSION_TIMEOUT.ago
              reset_session
              redirect_to sign_in_path, alert: "Your session has expired. Please sign in again."
            else
              @current_user.update(last_seen_at: Time.current)
            end
        end
    end
    def current_user
      @current_user
    end

    private
    
    
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    
    before_action :check_session_timeout
    before_action :set_friend, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user, only: [:edit, :update, :destroy]
  
    def index
      @friends = Friend.all
    end
  
    def show
    end
  
    def new
      @friend = Friend.new
    end
  
    def create
    
        @friend = current_user.friends.build(friend_params)
        if @friend.save
            redirect_to @friend, notice: 'Woooh, new friend created'
        else
            render :new, status: :unprocessable_entity
        end
        
    end
  
    def edit
    end
  
    def update
      if @friend.update(friend_params)
        redirect_to @friend, notice: 'Friend was updated successfully.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      first_name = @friend.first_name
      @friend.destroy
      redirect_to friends_url, notice: "#{first_name} was successfully removed."
    end
  
    private
  
    def set_friend
      @friend = Friend.find(params[:id])
    end
  
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :contact_number)
    end
  
    def authorize_user
      unless @friend.user == current_user
        redirect_to friends_path, alert: 'You are not authorized to perform this action'
      end
    end
  
    def current_user
      @current_user = Current.user
    end
  
    
  
    
  end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
    before_action :user_logged_in?
    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :user_logged_in?
    

    def edit

    end
    
    def update
        if Current.user.update(password_params)
            redirect_to root_path ,notice: 'Updated password successfully'
        else
            render :edit ,status: :unprocessable_entity
        end
    end


    
    private 
    def password_params
        params.require(:user).permit(:password,:password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        session[:session_id] = request.session.id
        session[:session_token] = @user.session_token
        session[:last_seen_at] = Time.current
        redirect_to root_path, notice: "Successfully created User"
      else
        render :new, status: :unprocessable_entity
      end
    end
    
      
   
    
      private
        
        def user_params
          params.require(:user).permit(:email, :password, :password_confirmation)
        end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :check_session_timeout, only: [:new, :create]
    def new

    end
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            user.create_session_token
            user.update(last_seen_at: Time.current)
            session[:session_token] = user.session_token
            Rails.logger.info "----------------------------------------------------------------------------------------------------------"
            Rails.logger.info "user info #{user.inspect}"
            Rails.logger.info "session details #{session.inspect}"
            Rails.logger.info "----------------------------------------------------------------------------------------------------------"
            
            redirect_to root_path,notice: "logged in successfully"
        else
            flash[:alert] = "Not valid"
            render :new ,status: :unprocessable_entity
        end
    end
    def edit
    end
    def destroy
        current_user.update(session_token: nil)
        reset_session        
        redirect_to sign_in_path , notice:'Logged out'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/edit.html.erb
<h1><%= action_name.capitalize %> Friend</h1>
<%= render 'shared/form' %>
<%= link_to 'Back', friends_path ,class:'btn btn-secondary mt-3'%>

app/views/friends/index.html.erb
<h1>Friends 😊</h1>
<% if Current.user %>
  <%= link_to 'New Friend', new_friend_path ,class:'btn btn-primary'%>
<% else %>
  <span ><i> <%= link_to 'LogIn' ,sign_in_path ,style:'text-decoration:none'%> or <%= link_to 'SignUp' ,sign_up_path ,style:'text-decoration:none'%> to add friends</i></span>
<% end %>
<!-- <%= @friends %> -->
<% if @friends.empty? %>
  <div class="card mt-3">
    <div class="card-body">
      <h3>Hey Buddy , Let's make new Friend's 😎
        !!</h3>
    </div>
  </div>
<% else %>

  <table  class="table table-bordered mt-3">
    <thead class="thead-light">
      <tr class="text-center">
        <th scope="col"> First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact Number</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr class="text-center">
          <td><%= friend.first_name  %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.contact_number %></td>
          <td><%= link_to 'Show', friend ,class:'btn btn-secondary'%></td>
          <% if friend.user == Current.user %>
            <td><%= link_to 'Edit', edit_friend_path(friend) ,class:'btn btn-secondary'%></td>
            <td><%= button_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger ' %></td>
          <% else %>
          <td></td><td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/friends/new.html.erb
<h1><%= action_name.capitalize %> Friend</h1>
<%= render 'shared/form' %>
<%= link_to 'Back', friends_path ,class:'btn btn-secondary mt-3'%>

app/views/friends/show.html.erb
<div class="card">
  <div class="card-body">
      <h1><%= @friend.first_name %> <%= @friend.last_name %></h1>
      <p> <b >Email:</b> <%= @friend.email %></p>
      <p> <b>Contact Number: </b> <%= @friend.contact_number %></p>
      <%= link_to 'Back', friends_path ,class:'btn btn-secondary'%>
      <% if @friend.user == Current.user %>
        <%= link_to 'Edit', edit_friend_path(@friend) ,class:'btn btn-secondary'%> 
        <%= button_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger mt-2' %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial:'shared/navbar' %>
    <div class="container">
      <!-- <p>Session ID: <%= session.id %></p> -->
        <%= render partial:'shared/flash' %>
        <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="text-primary">i'm at main page</h1>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: @friend, local: true) do |form| %>
  <!-- <% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </div>
  <% end %> -->
  <!-- <%= form.object.inspect %> -->
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">The following errors occurred:</h4>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field mb-3">
    <%= form.text_field :first_name, class: "form-control" ,placeholder: 'First name' %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :last_name, class: "form-control" ,placeholder: 'Last name'%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :email, class: "form-control" ,placeholder: 'example@gmail.com'%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :contact_number, class: "form-control" ,placeholder: 'Contact number'%>
  </div>

  <div class="actions ">
    <%= form.submit "Add friend",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
    <!-- <a class="navbar-brand" href="/">Navbar</a> -->
    <%= link_to "Friends" , root_path ,class:"navbar-brand ms-3"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="/">Home </a><a class="nav-link" href="/">Home </a>  
          <%= link_to "Home", root_path ,class:"nav-link" %>
        </li> -->
       

       
        
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-3">
        <% if Current.user %>
        <li class="nav-item active">
            
          <%= link_to Current.user.email, edit_password_path ,class: 'nav-link' %>
        </li>
          <li class="nav-item active">
              
            <%= button_to "Sign Out", logout_path ,method: :delete ,class:"nav-link" %>
          </li>
         
        <% else %>
          <li class="nav-item active">
            
            <%= link_to "Sign up", sign_up_path ,class:"nav-link" %>
          </li>
          <li class="nav-item active">
          
            <%= link_to "Sign In", sign_in_path ,class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>